### ISSUE TITLE
no such file or directory error

### ISSUE THREAD

**Issue by bradcrispin** [Sanjo/meteor-long-running-child-process#9]
A team member and I are working from the same versions but my build is throwing an error per closed sanjo:jasmine issue #279 sanjo_long-running-child-process error 

Our versions:

```
meteor-tool@1.1.10    
velocity:core@0.10.8
sanjo:long-running-child-process@1.1.3
OS X 10.11.1
```

My VELOCITY_DEBUG log: 

```
I20151112-16:57:17.942(-8)? server-internal
I20151112-16:57:17.942(-8)? Exception in callback of async function:
I20151112-16:57:17.943(-8)? error: 
I20151112-16:57:17.943(-8)? {"message":"Exception in callback of async function:","stack":"Error: ENOENT, no such file or directory '/Users/bradcrispin/code/node/meteor/parlay/.meteor/local/.meteor/local/build/programs/server/assets/packages/sanjo_long-running-child-process/lib/spawnScript.js'\n    at Object.fs.chmodSync (fs.js:833:18)\n    at LongRunningChildProcess.sanjo.LongRunningChildProcess.LongRunningChildProcess.spawn (meteor://💻app/packages/sanjo_long-running-child-process/packages/sanjo_long-running-child-process.js:275:1)\n    at _startMirror (meteor://💻app/src/methods/mirrors/mirror_request.js:207:15)\n    at meteor://💻app/src/methods/mirrors/mirror_request.js:104:7\n    at runWithEnvironment (meteor://💻app/packages/meteor/dynamics_nodejs.js:110:1)","uid":null}
I20151112-16:57:17.944(-8)? Exception in callback of async function: Error: ENOENT, no such file or directory '/Users/bradcrispin/code/node/meteor/parlay/.meteor/local/.meteor/local/build/programs/server/assets/packages/sanjo_long-running-child-process/lib/spawnScript.js'
I20151112-16:57:17.944(-8)?     at Object.fs.chmodSync (fs.js:833:18)
I20151112-16:57:17.944(-8)?     at LongRunningChildProcess.sanjo.LongRunningChildProcess.LongRunningChildProcess.spawn (meteor://💻app/packages/sanjo_long-running-child-process/packages/sanjo_long-running-child-process.js:275:1)
I20151112-16:57:17.944(-8)?     at _startMirror (meteor://💻app/src/methods/mirrors/mirror_request.js:207:15)
I20151112-16:57:17.944(-8)?     at meteor://💻app/src/methods/mirrors/mirror_request.js:104:7
I20151112-16:57:17.944(-8)?     at runWithEnvironment (meteor://💻app/packages/meteor/dynamics_nodejs.js:110:1)
```

Team member: 

```
I20151112-19:53:32.160(-5)? [velocity] Mirror process forked with pid 73471
I20151112-19:53:32.160(-5)? [velocity] cucumber is starting a mirror at http://localhost:53887/.
I20151112-19:53:32.169(-5)? [velocity] You can see the mirror logs at: tail -f /Users/me/parlay/.meteor
```

**Comment by lorensr** [comment]
xolvio/meteor-jasmine#279

**Comment by Sanjo** [comment]
Hi, I don't know how this error is produced. The wrong part in the path is the double ".meteor/local/.meteor/local". Can you try `meteor reset` and make sure that you start the app from the main app directory. Let me know if that works.

**Comment by bradcrispin** [comment]
`Meteor reset` did not resolve the error but deleting `rm -rf .meteor` did. Thank you!
